name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "hello"

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: print hello
        run: echo "hello2"
